description: llmserve-notebook
environment:
  image:
    cpu: determinedai/environments:cuda-11.8-pytorch-2.0-gpu-0.24.0
    gpu: determinedai/environments:cuda-11.8-pytorch-2.0-gpu-0.24.0
resources:
  slots: 1
  resource_pool: RTXA6000
bind_mounts:
  - host_path: /home/nfs_data_02
    container_path: /root1
  - host_path: /home/nfs_data
    container_path: /root2
idle_timeout: 30m

